name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust to match the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${ { secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: "ec2-35-157-168-13.eu-central-1.compute.amazonaws.com"
        REMOTE_USER: ec2-user
        TARGET: "/home/ec2-user/"
    